### ISSUE TITLE
do changes

### ISSUE THREAD

**Issue by UDAYAGIRICHARAN** [NEERAJAP2001/SE#9]
do changes in class and object diagram update delivery system

**Comment by NEERAJAP2001** [comment]
@UDAYAGIRICHARAN  Please be specific in points what changes do u need?

**Comment by UDAYAGIRICHARAN** [comment]
add class, catalogue diagrams and  make changes in the object diagram connect order and cart  and add catalogue

**Comment by NEERAJAP2001** [comment]
https://github.com/NEERAJAP2001/SE/blob/main/Book%20Store%20class.mdj Chech this

**Comment by UDAYAGIRICHARAN** [comment]
changes in the class diagram
add delivery  class
add catalogue class and connect with cart

changes in the object diagram
connect order and cart 
add delivery at last and catalogue before cart

**Comment by NEERAJAP2001** [comment]
@UDAYAGIRICHARAN Done
